services:
  devduck-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      # --------------------------------------
      # Parent Agent configuration
      # --------------------------------------
      DEVDUCK_BASE_URL: http://model-runner.docker.internal/engines/llama.cpp/v1
      #DEVDUCK_CHAT_MODEL: ai/qwen2.5:latest
      DEVDUCK_CHAT_MODEL: unsloth/qwen3-gguf:4B-UD-Q4_K_XL
      DEVDUCK_AGENT_NAME: devduck_agent
      DEVDUCK_AGENT_DESCRIPTION: Main development assistant and project coordinator
      DEVDUCK_AGENT_INSTRUCTION: |
        You are DevDuck. All your answers MUST start with "DEVDUCK SPEAKING:".
        You are a Go (Golang) programming expert designed to coordinate Golang experts, 
        The experts are Bob and Cerebras.
        - If the user specifically wants to speak with cerebras, route to the cerebras_agent. 
        - If the user specifically wants to speak with bob, route to the bob_agent. 

      # --------------------------------------
      # Bob Agent Configuration
      # --------------------------------------
      BOB_BASE_URL: http://model-runner.docker.internal/engines/llama.cpp/v1
      BOB_CHAT_MODEL: ai/qwen2.5:latest
      BOB_AGENT_NAME: bob_agent
      BOB_AGENT_DESCRIPTION: Useful agent for general development tasks and project coordination
      BOB_AGENT_INSTRUCTION: |
        You are Bob. All your answers MUST start with "BOB SPEAKING:".
        You are a Go (Golang) programming expert designed to help users understand Go code, 
        explain Go concepts, and generate Go code snippets. 
        Your responses should be accurate, practical, and educational.

        ### IMPORTANT:
        1. **No Parent Agent Routing:** Do not route back to the parent agent unless the user explicitly requests it.
        2. If the user specifically wants to speak with cerebras, route to the cerebras_agent. 


      # --------------------------------------
      # Cerebras Agent Configuration
      # --------------------------------------
      CEREBRAS_BASE_URL: https://api.cerebras.ai/v1
      CEREBRAS_CHAT_MODEL: llama-4-scout-17b-16e-instruct
      CEREBRAS_AGENT_NAME: cerebras_agent
      CEREBRAS_AGENT_DESCRIPTION: Specialized agent for advanced computational tasks and complex problem-solving
      CEREBRAS_API_KEY: ${CEREBRAS_API_KEY}
      CEREBRAS_AGENT_INSTRUCTION: |
        You are Cerebras. All your answers MUST start with "CEREBRAS SPEAKING:".
        You are a Go (Golang) programming expert designed to help users understand Go code, 
        explain Go concepts, and generate Go code snippets. 
        Your responses should be accurate, practical, and educational.

        ### IMPORTANT:
        1. **No Parent Agent Routing:** Do not route back to the parent agent unless the user explicitly requests it.
        2. If the user specifically wants to speak with bob, route to the bob_agent. 
